// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *about_us → Team members*
 */
export interface AboutUsDocumentDataTeamMembersItem {
  /**
   * Team member photo field in *about_us → Team members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.team_members[].team_member_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  team_member_photo: prismic.ImageField<never>;

  /**
   * Team member name field in *about_us → Team members*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.team_members[].team_member_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  team_member_name: prismic.TitleField;

  /**
   * Team member email field in *about_us → Team members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.team_members[].team_member_email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  team_member_email: prismic.KeyTextField;

  /**
   * Team member title field in *about_us → Team members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.team_members[].team_member_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  team_member_title: prismic.KeyTextField;
}

/**
 * Content for about_us documents
 */
interface AboutUsDocumentData {
  /**
   * Heading field in *about_us*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Content field in *about_us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Team members heading field in *about_us*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.team_members_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  team_members_heading: prismic.TitleField;

  /**
   * Team members field in *about_us*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.team_members[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_members: prismic.GroupField<
    Simplify<AboutUsDocumentDataTeamMembersItem>
  >;
}

/**
 * about_us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

/**
 * Item in *beliefs → Beliefs*
 */
export interface BeliefsDocumentDataBeliefsItem {
  /**
   * Belief heading field in *beliefs → Beliefs*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: beliefs.beliefs[].belief_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  belief_heading: prismic.TitleField;

  /**
   * Belief content field in *beliefs → Beliefs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: beliefs.beliefs[].belief_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  belief_content: prismic.RichTextField;
}

/**
 * Content for beliefs documents
 */
interface BeliefsDocumentData {
  /**
   * Heading field in *beliefs*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: beliefs.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Beliefs field in *beliefs*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: beliefs.beliefs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  beliefs: prismic.GroupField<Simplify<BeliefsDocumentDataBeliefsItem>>;
}

/**
 * beliefs document from Prismic
 *
 * - **API ID**: `beliefs`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BeliefsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BeliefsDocumentData>,
    "beliefs",
    Lang
  >;

/**
 * Item in *church → Sections*
 */
export interface ChurchDocumentDataSectionsItem {
  /**
   * Section heading field in *church → Sections*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: church.sections[].section_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_heading: prismic.TitleField;

  /**
   * Section content field in *church → Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: church.sections[].section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;
}

/**
 * Content for church documents
 */
interface ChurchDocumentData {
  /**
   * Heading field in *church*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: church.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *church*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: church.subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.TitleField;

  /**
   * Sections field in *church*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: church.sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<Simplify<ChurchDocumentDataSectionsItem>>;
}

/**
 * church document from Prismic
 *
 * - **API ID**: `church`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChurchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ChurchDocumentData>,
    "church",
    Lang
  >;

/**
 * Content for connect_adult documents
 */
interface ConnectAdultDocumentData {
  /**
   * Heading field in *connect_adult*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_adult.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *connect_adult*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_adult.subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.TitleField;

  /**
   * Content field in *connect_adult*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_adult.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * connect_adult document from Prismic
 *
 * - **API ID**: `connect_adult`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConnectAdultDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConnectAdultDocumentData>,
    "connect_adult",
    Lang
  >;

/**
 * Content for connect_children documents
 */
interface ConnectChildrenDocumentData {
  /**
   * Heading field in *connect_children*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_children.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *connect_children*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_children.subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.TitleField;

  /**
   * Content field in *connect_children*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_children.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * connect_children document from Prismic
 *
 * - **API ID**: `connect_children`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConnectChildrenDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConnectChildrenDocumentData>,
    "connect_children",
    Lang
  >;

/**
 * Content for connect_youth documents
 */
interface ConnectYouthDocumentData {
  /**
   * Heading field in *connect_youth*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_youth.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Subheading field in *connect_youth*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_youth.subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.TitleField;

  /**
   * Content field in *connect_youth*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: connect_youth.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * connect_youth document from Prismic
 *
 * - **API ID**: `connect_youth`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConnectYouthDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConnectYouthDocumentData>,
    "connect_youth",
    Lang
  >;

/**
 * Content for event documents
 */
interface EventDocumentData {
  /**
   * Title field in *event*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Date/time field in *event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: event.date_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date_time: prismic.TimestampField;

  /**
   * End date/time field in *event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: event.end_date_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  end_date_time: prismic.TimestampField;

  /**
   * Display on homepage field in *event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.display_on_homepage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_on_homepage: prismic.BooleanField /**
   * Recurrence frequency field in *event*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: event.recurrence_frequency
   * - **Tab**: Recurrence
   * - **Documentation**: https://prismic.io/docs/field#select
   */;
  recurrence_frequency: prismic.SelectField<
    "Daily" | "Weekly" | "Monthly" | "Yearly"
  >;

  /**
   * Recurrence end date field in *event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.recurrence_end_date
   * - **Tab**: Recurrence
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  recurrence_end_date: prismic.DateField;
}

/**
 * event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Content for events documents
 */
interface EventsDocumentData {
  /**
   * Heading field in *events*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: events.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventsDocumentData>,
    "events",
    Lang
  >;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Heading field in *homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Service time field in *homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.service_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_time: prismic.TitleField;

  /**
   * Subheading field in *homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.subheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.TitleField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for image documents
 */
interface ImageDocumentData {
  /**
   * Image field in *image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Display on homepage field in *image*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.display_on_homepage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_on_homepage: prismic.BooleanField;
}

/**
 * image document from Prismic
 *
 * - **API ID**: `image`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ImageDocumentData>, "image", Lang>;

/**
 * Content for Kids Big Event documents
 */
interface KidsBigEventDocumentData {
  /**
   * Kids Big Event 2022 field in *Kids Big Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kids_big_event.kids_big_event_2022
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  kids_big_event_2022: prismic.ImageField<never>;
}

/**
 * Kids Big Event document from Prismic
 *
 * - **API ID**: `kids_big_event`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KidsBigEventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KidsBigEventDocumentData>,
    "kids_big_event",
    Lang
  >;

/**
 * Item in *layout → Links*
 */
export interface LayoutDocumentDataLinksItem {
  /**
   * Link text field in *layout → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link route field in *layout → Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links[].link_route
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_route: prismic.ContentRelationshipField<
    | "beliefs"
    | "about_us"
    | "sermons"
    | "events"
    | "church"
    | "connect_children"
    | "connect_youth"
    | "connect_adult"
    | "messages"
  >;

  /**
   * DIsplay in header field in *layout → Links*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: layout.links[].display_in_header
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_in_header: prismic.BooleanField;

  /**
   * Display in footer field in *layout → Links*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: layout.links[].display_in_footer
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_in_footer: prismic.BooleanField;
}

/**
 * Content for layout documents
 */
interface LayoutDocumentData {
  /**
   * ID field in *layout*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  id: prismic.TitleField;

  /**
   * Links field in *layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<LayoutDocumentDataLinksItem>>;

  /**
   * Name field in *layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Location field in *layout*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;

  /**
   * Address field in *layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Email field in *layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;

  /**
   * Phone field in *layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone: prismic.RichTextField;
}

/**
 * layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

/**
 * Content for messages documents
 */
interface MessagesDocumentData {
  /**
   * Heading field in *messages*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: messages.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Deployment increment field in *messages*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: messages.deployment_increment
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  deployment_increment: prismic.NumberField;
}

/**
 * messages document from Prismic
 *
 * - **API ID**: `messages`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MessagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MessagesDocumentData>,
    "messages",
    Lang
  >;

/**
 * Content for video documents
 */
interface VideoDocumentData {
  /**
   * Video field in *video*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;

  /**
   * Display on homepage field in *video*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: video.display_on_homepage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_on_homepage: prismic.BooleanField;
}

/**
 * video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<VideoDocumentData>, "video", Lang>;

export type AllDocumentTypes =
  | AboutUsDocument
  | BeliefsDocument
  | ChurchDocument
  | ConnectAdultDocument
  | ConnectChildrenDocument
  | ConnectYouthDocument
  | EventDocument
  | EventsDocument
  | HomepageDocument
  | ImageDocument
  | KidsBigEventDocument
  | LayoutDocument
  | MessagesDocument
  | VideoDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataTeamMembersItem,
      BeliefsDocument,
      BeliefsDocumentData,
      BeliefsDocumentDataBeliefsItem,
      ChurchDocument,
      ChurchDocumentData,
      ChurchDocumentDataSectionsItem,
      ConnectAdultDocument,
      ConnectAdultDocumentData,
      ConnectChildrenDocument,
      ConnectChildrenDocumentData,
      ConnectYouthDocument,
      ConnectYouthDocumentData,
      EventDocument,
      EventDocumentData,
      EventsDocument,
      EventsDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      ImageDocument,
      ImageDocumentData,
      KidsBigEventDocument,
      KidsBigEventDocumentData,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataLinksItem,
      MessagesDocument,
      MessagesDocumentData,
      VideoDocument,
      VideoDocumentData,
      AllDocumentTypes,
    };
  }
}
