// export * from './headings'
export {default as Article} from './article'
export {default as Container} from './container'
export {default as H2Kicker} from './h2-kicker'
export {default as HtmlContent} from './html-content'
export {default as Layout} from './layout'
export {default as MessageSeries} from './message-series'
export {default as MessageStandalone} from './message-standalone'
export {default as MessageVideo} from './message-video'
export {default as Pagination} from './pagination'
// export {default as SEO} from './SEO'
export {default as Small} from './small'
export {default as UnorderedList} from './unordered-list'
